#Installs a check to test access to DD HQ via https-proxy
#Dependencies: Datadog agent 5.14.0 and https-proxy enabled
#For all the applicable settings for a speciifc check (instance) refer the example config
---
- name: Check if values for all the template variables are set
  fail: msg="env_name,cluster_name etc have to be set"
  when: env_name is not defined or cluster_name is not defined

- name: Generate the instance entry
  template: src=http_check.yaml.conf.j2 dest=/tmp/http_check.yaml 
  
- name: Append http_check config to /etc/dd-agent/conf.d/http_check.yaml
  shell: grep "Verify DataDog HQ Access" /etc/dd-agent/conf.d/http_check.yaml || cat /tmp/http_check.yaml >>/etc/dd-agent/conf.d/http_check.yaml
